### PR TITLE
Support symbolic links

### PR DESCRIPTION
**Pull request by fzgregor**
Hi @woelper,

thank you for providing `dircpy`! I notice it ignores symbolic links at the moment. Only files and directories are handled.

I implemented the necessary functionality. Note that I had to use `path.symlink_metadata().is_ok()` to check if a file exists, as `path.exists()` follows symbolic links. That is, if the symbolic link was dangling, it would return `false` and the link wouldn't be copied. Also, `metadata()` would follow symbolic links, which is not what we want here.

### CODE REVIEW

**Comment by woelper** [comment]
Nice, thanks! Wow, I would have never guessed that `symlink_metadata()` Queries the metadata about a file *without* following symlinks. I'll merge this PR, but I think I might add a test before I release. If you want to write one, feel free to do so!

**Comment by fzgregor** [comment]
Does this #5 work for you?

**Comment by woelper** [comment]
Thanks, yes. Merged #5 . Nice work!
I like the functionality as it is now as default - it basically recreates a folder 1:1.

As for ergonomics, do you think it makes sense to add options to skip symlinks or dereference them? Or is this something people will not need?

**Comment by woelper** [comment]
Crates.io version has been released.

**Comment by fzgregor** [comment]
> Crates.io version has been released.

Nice! Thanks

> As for ergonomics, do you think it makes sense to add options to skip symlinks or dereference them? Or is this something people will not need?

I was thinking about this as well. Typically, symbolic links convey some semantics. E.g., one might use a symlink to ensure the same content is found at various file paths. And wants to keep this invariant, even after some program modifies the file via one of the paths. Or to save space referencing a huge file from multiple paths.
There is the exception though of symbolic links that become dangling in the destination because they don't reference a path within the copied directory... 

I, personally, don't see the use for skipping symbolic links, dereferencing during copy might have its use though.

**Pull request merged**
